"""initial schema snapshot v1.2.0

Revision ID: e2a21139b806
Revises: 
Create Date: 2026-03-15 11:19:43.002300

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e2a21139b806'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schema_migrations')
    with op.batch_alter_table('guest_feedback', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('guest_feedback_token_key'), type_='unique')
        batch_op.drop_index(batch_op.f('idx_feedback_token'))
        batch_op.create_index(batch_op.f('ix_guest_feedback_token'), ['token'], unique=True)

    with op.batch_alter_table('guests', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['phone'])

    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_reservations_booking_ref'))

    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.alter_column('payment_summary',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.alter_column('payment_summary',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)

    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_reservations_booking_ref'), ['booking_reference'], unique=False)

    with op.batch_alter_table('guests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('guest_feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guest_feedback_token'))
        batch_op.create_index(batch_op.f('idx_feedback_token'), ['token'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('guest_feedback_token_key'), ['token'], postgresql_nulls_not_distinct=False)

    op.create_table('schema_migrations',
    sa.Column('version', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('applied_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('version', name=op.f('schema_migrations_pkey'))
    )
    # ### end Alembic commands ###
